### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by erceguder** [arnabkmondal/GenDA#1]
Greetings @arnabkmondal ,

After reading the paper, and having a look at the code, I am confused on the following regard: why do we have two different `w` variables, namely `w_target` and `w_noise`? 

Thanks

**Comment by arnabkmondal** [comment]
Hi, Initially we were using embedding of the target images, `w_target` concatenated with Gaussian noise, `w_noise`. Later during ablation, we removed the embedding step as simple Gaussian noise also achieves similar performance. However, in the code, instead of using a single Gaussian noise I have changed the `w_target` with another Gaussian noise to avoid changing the remaining code. Hope this clarifies.

**Comment by erceguder** [comment]
@arnabkmondal Thank you for the clarification.

Indeed, I was trying to fully understand the algorithm, yet the pseudo-code found in the paper looked a bit ambiguous to me. Then, I've started examining the code, which was not really helpful neither 🙂 I would really appreciate if you could share a more specific pseudo-code of the algorithm here. Thanks, again, in advance.
